name: portfolio
description: "Vijay Arther - Software Developer Portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
